# Generated by Django 2.2.10 on 2021-05-15 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plcount', '0003_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='nif_company',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
