# Generated by Django 2.2.10 on 2021-05-20 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plcount', '0004_auto_20210516_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='fluxo',
            name='data',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='fluxo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
