# Generated by Django 2.2.10 on 2021-05-22 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plcount', '0008_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
