# Generated by Django 2.2.10 on 2021-05-23 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plcount', '0011_auto_20210523_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='nif_company',
            field=models.IntegerField(max_length=9),
        ),
    ]
