# Generated by Django 2.2.10 on 2021-05-23 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plcount', '0013_auto_20210523_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('context', models.CharField(max_length=500)),
            ],
        ),
    ]
