# Generated by Django 2.2.10 on 2021-05-23 22:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import plcount.validator


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plcount', '0014_home'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('report', models.FileField(upload_to='report/%y', validators=[plcount.validator.file_size])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
