# Generated by Django 2.2.10 on 2021-05-24 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plcount', '0015_report'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='fluxo',
            table='data',
        ),
    ]
