# Generated by Django 2.2.10 on 2021-05-24 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plcount', '0016_auto_20210524_1846'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='fluxo',
            table=None,
        ),
    ]
