# Generated by Django 2.2.10 on 2021-05-26 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plcount', '0017_auto_20210524_1848'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='context',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='caption',
            new_name='name_company',
        ),
    ]
